Task 7
trikey/test-guru pull request #7
Opened 2017-12-13 21:32 UTC by trikey

К сожалению дизайна там нет никакого, очень извиняюсь за это, но пока не смог найти на него время. Обязательно займусь им в выходные.
Думаю, что сделаю на bootstrap

2017-12-14 12:07 UTC, psylone requested changes
Нет проблем с вёрсткой - впереди будет отдельное занятие относительно Bootstrap, так что сейчас с вёрсткой можно не заморачиваться.

2017-12-14 12:07 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render 'tests/show'
Если выводим коллекцию вопросов на странице теста, этот экшен нам не нужен.

2017-12-14 12:07 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @test = @question.test
Не стоит определять `@test` в методе который называется `find_question`.

2017-12-14 12:07 UTC, psylone commented on app/controllers/tests_controller.rb
> +    @questions = @test.questions
То же самое здесь: метод `find_test` отвечает за поиск теста. В принципе, все связанные объекты мы можем выбрать по ассоциации, можно не сохранять эти связанные объекты в отдельных инстанс-переменных.

2017-12-14 12:07 UTC, psylone commented on app/helpers/questions_helper.rb
> +    if question.id.nil?
Есть удобный метод `new_record?`

2017-12-14 12:07 UTC, psylone commented on app/helpers/questions_helper.rb
> +  def question_header(question, test)
Достаточно передать `question`, тест можно взять с помощью ассоциации.

2017-12-14 12:07 UTC, psylone commented on app/views/questions/_form.html.erb
> +  <% end %>
Ошибки нужно вынести во фрагмент представления (паршиал).

2017-12-14 12:07 UTC, psylone commented on app/views/questions/_form.html.erb
> +  <%= hidden_field_tag 'question[test_id]', @test.id  %>
Этого тэга быть не должно. Вопрос должен связываться с тестом через ассоциацию. Для этого можно использовать такой способ создания объекта вопроса: `@question = @test.questions.new`. В этом случае `test_id` у вопроса установится автоматически.

2017-12-14 12:07 UTC, psylone commented on app/views/questions/new.html.erb
> +<%= render 'form', { model: [@test, @question] } %>
Нет необходимости передавать локальную переменную `model` (хотя идея правильная), Рельсы сами обработают корректно случай если `@test` окажется со значением `nil`.

2017-12-14 12:07 UTC, psylone commented on app/views/shared/_footer.html.erb
> +    <p><%= github_url 'Test Guru', 'https://github.com/trikey/test-guru' %></p>
Вызов хэлпера должен выглядеть примерно так: `github_url 'trikey', 'test-guru'`. Можно добавить 3-й параметр с тем текстом который будет отображаться в ссылке. То есть смысл хэлпера в том чтобы сконструировать URL по заданным параметрам.

2017-12-14 12:07 UTC, psylone commented on app/views/tests/show.html.erb
> +  <% @test.questions.each do |question| %>
Рендеринг коллекции связанных вопросов лучше делать через фрагмент представления.

2017-12-14 12:07 UTC, psylone commented on app/views/tests/index.html.erb
> +    <% @tests.each do |test| %>
Здесь тоже можно рендеринг коллекции тестов сделать с помощью фрагментов представления.

2017-12-14 12:07 UTC, psylone commented on app/views/questions/new.html.erb
> +<h2><%= question_header @question, @test %></h2>
Достаточно передать `@question`.

2017-12-14 12:07 UTC, psylone commented on app/controllers/tests_controller.rb
> +    Test.destroy(params[:id])
Чаще во время удаления работают с объектом: `@test.destroy`, вместо класса.

2017-12-14 12:07 UTC, psylone commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
Нет необходимости передавать явно `:test_id` в параметрах. Обычно у нас либо есть объект теста, либо `:test_id` уже установлен (например, в случае редактирования вопроса).

2017-12-14 12:07 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @question = Question.new
Используй ассоциацию для создания нового объекта вопроса: `@question = @test.questions.new`.

2017-12-14 12:07 UTC, psylone commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path(@test)
Здесь лучше редиректить на страницу просмотра связанного теста.

2017-12-15 00:19 UTC, psylone approved these changes

2017-12-15 00:19 UTC, psylone commented on app/controllers/questions_controller.rb
Подозреваю что коллекция тестов здесь не нужна. В любом случае, метод лучше назвать в единственном числе: `find_test`.

2017-12-15 00:19 UTC, psylone commented on app/helpers/footer_helper.rb
> +    link_to text, "https://github.com/#{author}/#{repo}", target: :_blank
👍

2017-12-15 00:19 UTC, psylone commented on app/helpers/questions_helper.rb
> +      "Edit #{question.test.title} Question"
Другое дело!

2017-12-15 00:19 UTC, psylone commented on config/routes.rb
> +    resources :questions
Опция `shallow: true` всё же пригодится )

2017-12-15 04:51 UTC, trikey commented on config/routes.rb
> +    resources :questions
Да, мне и самому кажется, что без нее будет лучше. но увы, тогда form_with ругается на отсутствие метода testq_qeustion_path в момент редактирования вопроса, мы ведь ему скармливаем model: [@question.test, @question], а роута подходящего у нас нет с опцией shallow

вот все роуты, которые выдаются с опцией shallow:
http://joxi.ru/n2Y8wDEfo88o6m

вот сама ошибка:
http://joxi.ru/Vm6yN0wuDPPD9r

2017-12-15 07:46 UTC, merged

2017-12-15 11:59 UTC, psylone commented on app/views/questions/_form.html.erb
> +<%= form_with model: [@test, @question], local: true do |form| %>
👍